eureka:
  context-path: /my-eureka-server
  single-instance:
    host: localhost
    port: 9099
  client:
    service-url: 
      defaultZone: http://${eureka.single-instance.host}:${eureka.single-instance.port}${eureka.context-path}/eureka
  instance:
    statusPageUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: zuul-api-gateway

server:
  servlet:
    context-path: /zuul-gateway
  port: 9090
  error:
    whitelabel:
      enabled: true

info:
  app-name: ${spring.application.name}
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

# Zuul Configuration
zuul:
  ribbon-isolation-strategy: semaphore
  ignored-services: uppercase-microservice
  routes:
    upper:
      path: /upper/**
      service-id: uppercase-microservice
      # strip-prefix: true #StripPrefix default is true
      
      # If wants to route to /upper/toUppercase/{name} in uppercase-microservice needs strip-prefix: false
      strip-prefix: false
      


logging:
  level:
    #org.apache.http: DEBUG 
    org.springframework.cloud: INFO
    com.netflix.loadbalancer: OFF
#mvn spring-boot:run -Dspring-boot.run.profiles=client-in-single-eureka -Dspring-boot.run.arguments=--server.port=55991
