#server:
  #servlet:
    #context-path: /hello-config-client
  #port: 9091
  
# Spring application properties
spring:
  application:
    name: HelloService
  profiles:
    active: dev
  
  # 1. Agregar dependencias para Spring Cloud Bus
  # 2. Agregar configuración para RabbitMQ
  #rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: '{cipher}9e5ae1cc5e41cc8a48b10030cc3edbd4459f35560cb138797965aa7a4997e2c6'

#management:
  #endpoints:
    #web:
      #exposure:
        #include: bus-refresh,bus-env

hello:
  message: XXX

#guest: '{cipher}9e5ae1cc5e41cc8a48b10030cc3edbd4459f35560cb138797965aa7a4997e2c6'
