# For single Eureka instance
server:
  port: 9099
  servlet:
    context-path: /my-eureka-server

spring:
  application:
    name: my-eureka-server
    
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      #base-path: /
      exposure:
        include: '*'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}${server.servlet.context-path}/eureka

#eureka.instance.hostname=${spring.cloud.client.hostname}
    
# 127.0.0.1 eureka-host1
# 127.0.0.1 eureka-host2
